# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ pretext-cli ]
    paths-ignore: 
      - '**.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Dependencies 
        run: |
          sudo apt-get update -y
          sudo apt install pdf2svg
          pip3 install pretextbook
          pip3 install lxml
          pip3 install requests
          pip3 install pdfCropMargins

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: TeX Dependencies
        run: |
          tlmgr --version
          tlmgr install $(cat latex-packages.txt)

      # Runs a single command using the runners shell
      - name: Build HTML Files
        run: |
          pretext build html -d

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/